version: '3.3'
services:
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: 'beer-service'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'userpassword'
      MYSQL_ROOT_PASSWORD: 'rootpassword'
    ports:
      - '3306:3306'
    volumes:
      - mssc-beer-service-db:/var/lib/mysql
volumes:
  mssc-beer-service-db: